let shinchanDatabase = [
{
    id: 1,
    name: "Nohara Shinnosuke 野原 - 新之助",
    dob: "May 5",
},
{   id: 2,
    name: "Nohara Himawari 野原 - ひまわり",
    dob: "Sep 27",
},
{   id: 3,
    name: "Nohara Misae 野原 - みさえ",
    dob: "Oct 10",
},
{   id: 4,
    name: "Nohara Hiroshi 野原 - ひろし",
    dob: "Unknown",
},
{   id: 5,
    name: "Nohara Shiro 野原 - シロ",
    dob: "Unknown",
},
{   id: 6,
    name: "Sakurada Nene 桜田 - ネネ",
    dob: "Jun 5",
},
{   id: 7,
    name: "Kazama Toru 風間 - トオル",
    dob: "Jul 19",
},
{   id: 8,
    name: "Sato Masao 佐藤 - マサオ",
    dob: "Feb 4",
},
{   id: 9,
    name: "Ikawa Botaro 井川 - 棒太郎",
    dob: "Sep 1",
},
{   id: 10,
    name: "Suotome Ai 酢乙女 - あい",
    dob: "Unknown",
},
]